
import { EnterpriseCategory, Enterprise } from './types';

export const CATEGORIES: { id: string; name: EnterpriseCategory; icon: string }[] = [
  { id: 'food', name: 'Food & Hospitality', icon: 'Utensils' },
  { id: 'health', name: 'Health & Wellness', icon: 'HeartPulse' },
  { id: 'tech', name: 'Technology & IT', icon: 'Cpu' },
  { id: 'business', name: 'Business & Professional', icon: 'Briefcase' },
  { id: 'home', name: 'Home & Lifestyle', icon: 'Home' },
  { id: 'creative', name: 'Creative & Media', icon: 'Palette' },
  { id: 'education', name: 'Education & Training', icon: 'GraduationCap' },
  { id: 'events', name: 'Events & Entertainment', icon: 'PartyPopper' },
];

/**
 * SAMPLE BUSINESSES
 * Verified records for Douala and Ngaoundéré.
 */
export const MOCK_BUSINESSES: Enterprise[] = [
  {
    id: "isstmadd-ngr",
    name: "Institut Supérieur ISSTMADD",
    businessName: "Institut Supérieur ISSTMADD",
    tagline: "Professional University Ngaoundéré",
    description: "L'ISSTMADD est une grande institution privée d’enseignement supérieur dont la vocation est la formation professionnelle des jeunes étudiants camerounais dans les domaines de la santé, des énergies renouvelables, et du management.",
    category: "Education & Training",
    address: "N1, BP: 391",
    city: "Ngaoundéré",
    state: "Adamawa",
    phoneNumber: "+237 693 351 905",
    whatsapp: "237693351905",
    email: "info@isstmadd.net",
    website: "https://isstmadd.net",
    hours: "Monday - Saturday: 08:00 AM - 08:30 PM",
    priceRange: "$$",
    logo: "https://picsum.photos/seed/isstmadd-logo/400/400",
    coverPhoto: "https://images.unsplash.com/photo-1541339907198-e087563f3f2b?q=80&w=1200",
    latitude: 7.3277,
    longitude: 13.5847,
    averageRating: 4.4,
    totalReviews: 14,
    createdDate: new Date().toISOString(),
    isVerified: true,
    isActive: true,
    ownerId: "admin-system",
    ceoName: "Director ISSTMADD",
    employeeCount: "51-200",
    quarter: "Commercial Centre"
  },
  {
    id: "upsylone-dla",
    name: "UPSYLONE SARL",
    businessName: "UPSYLONE SARL",
    tagline: "Digital Solutions Agency",
    description: "Nous concevons et développons des solutions numériques évolutives et performantes pour répondre aux défis commerciaux de nos clients au Cameroun et en France. Spécialistes en création de sites web et applications mobiles.",
    category: "Technology & IT",
    address: "Lycée de Makepe, Douala",
    city: "Douala",
    state: "Littoral",
    phoneNumber: "+237 674 519 135",
    whatsapp: "237674519135",
    email: "contact@upsylone.com",
    website: "https://upsylone.com",
    hours: "Monday - Friday: 08:00 AM - 06:00 PM",
    priceRange: "$$$",
    logo: "https://picsum.photos/seed/upsylone-logo/400/400",
    coverPhoto: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=1200",
    latitude: 4.0511,
    longitude: 9.7679,
    averageRating: 4.7,
    totalReviews: 10,
    createdDate: new Date().toISOString(),
    isVerified: true,
    isActive: true,
    ownerId: "admin-system",
    ceoName: "Director Upsylone",
    employeeCount: "11-50",
    quarter: "Makepe"
  },
  {
    id: "douala-trade-center",
    name: "The Douala Trade Center",
    businessName: "The Douala Trade Center",
    tagline: "Professional Work Spaces",
    description: "Located in the heart of Akwa, we provide high-fidelity office spaces and professional consulting services for trade in Cameroon.",
    category: "Business & Professional",
    address: "Boulevard de la Liberté, Akwa",
    city: "Douala",
    state: "Littoral",
    phoneNumber: "+237 600 000 001",
    whatsapp: "237600000001",
    email: "trade@douala.cm",
    hours: "Monday - Friday: 08:00 AM - 06:00 PM",
    priceRange: "$$",
    logo: "https://picsum.photos/seed/dla-logo/200/200",
    coverPhoto: "https://images.unsplash.com/photo-1588334488081-06fca9a234f9?q=80&w=1200",
    latitude: 4.0448,
    longitude: 9.7042,
    averageRating: 5.0,
    totalReviews: 1,
    createdDate: new Date().toISOString(),
    isVerified: true,
    isActive: true,
    ownerId: "admin-system",
    ceoName: "Director Douala",
    employeeCount: "11-50",
    quarter: "Akwa"
  },
  {
    id: "ngr-plateau-lodge",
    name: "Ngaoundéré Plateau Lodge",
    businessName: "Ngaoundéré Plateau Lodge",
    tagline: "Quality Stay in the North",
    description: "Experience the beauty of the Adamawa Plateau. Our lodge offers the best hospitality and comfort for visitors to Ngaoundéré.",
    category: "Food & Hospitality",
    address: "Plateau District, near the Palace",
    city: "Ngaoundéré",
    state: "Adamawa",
    phoneNumber: "+237 600 000 002",
    whatsapp: "237600000002",
    email: "stay@ngr-lodge.cm",
    hours: "Monday - Sunday: Open 24 Hours",
    priceRange: "$$$",
    logo: "https://picsum.photos/seed/ngr-logo/200/200",
    coverPhoto: "https://images.unsplash.com/photo-1602685234860-3d38ee425ae8?q=80&w=1200",
    latitude: 7.3300,
    longitude: 13.5800,
    averageRating: 4.8,
    totalReviews: 1,
    createdDate: new Date().toISOString(),
    isVerified: true,
    isActive: true,
    ownerId: "admin-system",
    ceoName: "Manager Adamawa",
    employeeCount: "1-10",
    quarter: "Plateau"
  }
];

export const MOCK_REVIEWS = (bizId: string, bizName: string): any[] => [
  {
    id: `rev-${bizId}-1`,
    businessId: bizId,
    businessName: bizName,
    reviewerId: "sample-user-1",
    userName: "Ephraim",
    userPhoto: "https://i.pravatar.cc/150?u=ephraim",
    rating: 5,
    reviewText: "Excellent service and very professional approach. Highly recommended for trade and partnership.",
    photos: [],
    createdDate: new Date().toISOString(),
    isHelpfulCount: 0
  }
];
